sudo: required
services:
    - docker
before_install:
    - docker build -t mohammadarifmustafa/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true mohammadarifmustafa/docker-react npm run test