sudo: required
services:
    - docker

before_install:
    - docker build -t mohammadarifmustafa/docker-react -f Dockerfile.dev .
    - docker run --name docker-react mohammadarifmustafa/docker-react npm run test -- --coverage

script:
    - docker rm -f docker-react
        