sudo: required
services:
    - docker
before_install:
    - docker build -t mohammadarifmustafa/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true mohammadarifmustafa/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: elasticbeanstalk-us-east-2-270902472637
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ELASTICBEANSTALK_DOCKER_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_ELASTICBEANSTALK_DOCKER_SECRET_KEY"