sudo: required
services:
    - docker

before_install:
    - docker build -t mohammadarifmustafa/docker-react -f Dockerfile.dev .
    - docker run -it mohammadarifmustafa/docker-react npm run test -- --coverage

script:
    - q
        